# Chargement des données et des modules

In [1]:
# Chargement des librairies
import pandas as pd
import numpy as np

# Affichage propre des graphiques
%matplotlib inline

In [2]:
# Chargement des données
disasters = pd.read_csv("data/disasters_1900_2021.csv")
conflicts = pd.read_csv("data/conflicts.csv")
indicator_info = pd.read_csv("data/indicator_info.csv") # Ce dataset ne servira que d'un simple document supplémentaire pour comprendre les indicateurs dans le jeu de donnée Demographics
life_expectancy = pd.read_csv("data/demographic.csv", low_memory=False)
health_inequality = pd.read_excel("data/health_inequality.xlsx")

In [3]:
# Apercu du jeu de donnée Natural Disasters
disasters.head(5)

,Year,Seq,Glide,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Disaster Subsubtype,Event Name,Country,...,No Affected,No Homeless,Total Affected,Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Adm Level,Admin1 Code,Admin2 Code,Geo Locations
0,1900,9002,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,Cabo Verde,...,NaN,NaN,NaN,NaN,NaN,3.221647,NaN,NaN,NaN,NaN
1,1900,9001,NaN,Natural,Climatological,Drought,Drought,NaN,NaN,India,...,NaN,NaN,NaN,NaN,NaN,3.221647,NaN,NaN,NaN,NaN
2,1902,12,NaN,Natural,Geophysical,Earthquake,Ground movement,NaN,NaN,Guatemala,...,NaN,NaN,NaN,NaN,25000.0,3.350513,NaN,NaN,NaN,NaN
3,1902,3,NaN,Natural,Geophysical,Volcanic activity,Ash fall,NaN,Santa Maria,Guatemala,...,NaN,NaN,NaN,NaN,NaN,3.350513,NaN,NaN,NaN,NaN
4,1902,10,NaN,Natural,Geophysical,Volcanic activity,Ash fall,NaN,Santa Maria,Guatemala,...,NaN,NaN,NaN,NaN,NaN,3.350513,NaN,NaN,NaN,NaN

In [4]:
# Apercu du jeu de donnée Conflicts
conflicts.head(5)

,conflict_id,location,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,territory_name,...,ep_end,ep_end_date,ep_end_prec,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,region,version
0,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2012-12-21,NaN,750,NaN,NaN,NaN,750,3,25.1
1,11342,India,Government of India,141,NaN,GNLA,1163,NaN,1,Garoland,...,1,2014-11-27,NaN,750,NaN,NaN,NaN,750,3,25.1
2,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1967-06-10,NaN,651,NaN,666,NaN,"651, 666",2,25.1
3,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,0,NaN,NaN,651,NaN,666,NaN,"651, 666",2,25.1
4,11343,"Egypt, Israel",Government of Egypt,117,NaN,Government of Israel,121,NaN,1,Suez/Sinai,...,1,1970-08-07,NaN,651,NaN,666,NaN,"651, 666",2,25.1

In [5]:
# Apercu du jeu de donnée Info Supplémentaire
indicator_info.head(5)

,IndicatorNo,Topic,Indicator,IndicatorName,Unit
0,1,Population,TPopulation1Jan,"Total Population, as of 1 January",thousands
1,2,Population,TPopulation1July,"Total Population, as of 1 July",thousands
2,3,Population,TPopulationMale1July,"Male Population, as of 1 July",thousands
3,4,Population,TPopulationFemale1July,"Female Population, as of 1 July",thousands
4,5,Population,PopDensity,"Population Density, as of 1 July",persons per square km

In [6]:
# Apercu du jeu de donnée Demographic
life_expectancy.head(5)

,SortOrder,LocID,Notes,ISO3_code,ISO2_code,SDMX_code,LocTypeID,LocTypeName,ParentID,Location,...,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,NetMigrations,CNMR
0,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,654.5798,631.8067,297.6529,298.4483,297.2079,443.3215,457.3384,427.3167,201.196,2.907
1,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,642.5944,619.1788,292.4375,293.1236,292.0887,436.9979,451.4368,420.7398,195.070,2.760
2,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,630.8166,607.6061,286.6916,287.3395,286.3341,429.8298,444.5151,413.5565,182.671,2.529
3,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,619.9937,596.2667,281.4671,282.0251,281.1446,423.2008,438.1189,406.9265,164.189,2.222
4,NaN,5507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ADB region: Central and West Asia,...,610.3878,586.3428,276.8312,277.5799,276.2557,417.3453,432.7454,400.7629,163.064,2.157

In [7]:
health_inequality.head(5)

,setting,date,source,indicator_abbr,indicator_name,dimension,subgroup,estimate,se,ci_lb,...,iso3,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,whoreg6,wbincome2025,update,dataset_id
0,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,247.968162,NaN,194.625473,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
1,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Male,272.898981,NaN,214.032553,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
2,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Female,363.074361,NaN,286.019402,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
3,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Male,379.310303,NaN,297.924681,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
4,Afghanistan,1958,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,245.144576,NaN,197.317972,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho

# Nettoyage des données

## Pour le jeu de donnée "Natural Disasters"

### Ajout des filtres pour les intervalles de dates

### Sélection des colonnes utiles

In [8]:
disasters = disasters[['Year', 'Country', 'Disaster Type', 'Total Deaths', 'Total Affected']]

In [9]:
disasters.head(5)

   Year     Country      Disaster Type  Total Deaths  Total Affected
0  1900  Cabo Verde            Drought       11000.0             NaN
1  1900       India            Drought     1250000.0             NaN
2  1902   Guatemala         Earthquake        2000.0             NaN
3  1902   Guatemala  Volcanic activity        1000.0             NaN
4  1902   Guatemala  Volcanic activity        6000.0             NaN

### Renommage des colonnes

In [10]:
# Afin d'enlever les espaces 
disasters = disasters.rename(columns={
    'Year': 'Year',
    'Country': 'Country',
    'Disaster Type': 'Disaster_type',
    'Total Deaths': 'Total_deaths',
    'Total Affected': 'Total_affected'
})

### Filtrage de 1950-2021

In [11]:
disasters = disasters[disasters['Year'].between(1950,2021)]

### Gestion des valeurs manquantes

La valeur manquante dans le jeu de donnée peut autant signifier qu'il n'y a **pas eu de morts** dans le cas de la colonne **Total Deaths** ou que la donnée soit vraiment **manquante**.

In [12]:
# Regardons le nombre de valeurs manquantes de la colonne Total Deaths par type de catastrophe naturelle
print(disasters.groupby('Disaster_type')['Total_deaths'].apply(
    lambda x: x.isnull().sum()
).sort_values(ascending=False))

Disaster_type
Flood                    1507
Storm                    1156
Drought                   679
Earthquake                366
Wildfire                  270
Epidemic                  228
Volcanic activity         171
Extreme temperature       113
Insect infestation         93
Landslide                  35
Mass movement (dry)         2
Impact                      1
Animal accident             0
Fog                         0
Glacial lake outburst       0
Name: Total_deaths, dtype: int64

On remarque que les valeurs manquantes sont concentrées sur les 3 catastrophes naturelles: **inondation, tempête, sécheresse**. Ce qui est logique étant donné que ce sont les catastrophes naturelles **les moins mortelles** pour la population. Donc, les valeurs manquantes ici représentent réellement une donnée. Pour les comptabiliser, on va les remplacer par 0.

In [13]:
# Remplir les valeurs manquantes par 0
disasters['Total_deaths'] = disasters['Total_deaths'].fillna(0)
disasters['Total_affected'] = disasters['Total_affected'].fillna(0)

# Imputation par la médiane par type de catastrophe
columns = ['Total_deaths', 'Total_affected']

for col in columns:
    disasters[col] = disasters.groupby('Country')[col].transform(
        lambda x: x.fillna(x.median())
    )
    disasters[col] = disasters[col].fillna(disasters[col].median())

In [14]:
# Aggrégation par année et par pays
disasters_agg = disasters.groupby(['Country', 'Year']).agg(
    nb_disasters     = ('Disaster_type', 'count'),
    total_deaths_per_country = ('Total_deaths', 'sum'),
    total_affected   = ('Total_affected', 'sum')
).reset_index()

In [15]:
disasters_agg.head(5)

       Country  Year  nb_disasters  total_deaths_per_country  total_affected
0  Afghanistan  1954             1                    2000.0             0.0
1  Afghanistan  1956             2                     151.0          2000.0
2  Afghanistan  1963             1                     107.0             0.0
3  Afghanistan  1969             1                       0.0         48000.0
4  Afghanistan  1971             2                     100.0             0.0

## Pour le jeux de donnée "Conflicts"

### Renommage des colonnes

1 = Conflit mineur : entre 25 et 999 morts au combat au cours d'une année donnée. 2 = Guerre : au moins 1 000 morts au combat au cours d'une année donnée.

1 = extrasystémique (entre un État et un groupe non étatique situé hors de son propre territoire, où la partie gouvernementale lutte pour conserver le contrôle d'un territoire situé en dehors du système étatique) 2 = interétatique (les deux parties sont des États dans le système de classification de Gleditsch et Ward) 3 = intra-étatique (la partie A est toujours un gouvernement ; la partie B est toujours un ou plusieurs groupes rebelles ; il n'y a pas d'implication de gouvernements étrangers avec des troupes, c'est-à-dire qu'il n'y a pas de code side_a_2nd ou side_b_2nd) 4 = intra-étatique internationalisé (le camp A est toujours un gouvernement ; le camp B est toujours un ou plusieurs groupes rebelles ; il y a implication de gouvernements étrangers avec des troupes, c'est-à-dire qu'il y a au moins UN code side_a_2nd ou side_b_2nd)

In [16]:
conflicts = conflicts.rename(columns={
    'year' : 'year',
    'location': 'Country'
})

### Filtrage pour l'année 1950 jusqu'à 2021

In [17]:
conflicts =conflicts[conflicts['year'].between(1950, 2021)]

### Sélection des colonnes essentielles

In [18]:
conflicts =conflicts[['Country', 'year', 'intensity_level', 'type_of_conflict']]

In [19]:
conflicts.head(5)

         Country  year  intensity_level  type_of_conflict
0          India  2012                1                 3
1          India  2014                1                 3
2  Egypt, Israel  1967                2                 2
3  Egypt, Israel  1969                1                 2
4  Egypt, Israel  1970                1                 2

## Pour le jeu de donnée "Demographics"

### Sélection des colonnes nécessaires

In [20]:
life_expectancy = life_expectancy[['Location', 'Time', 'LEx', 'LExMale', 'LExFemale', 'Deaths','DeathsMale', 'DeathsFemale', 'IMR', 'PopGrowthRate', 'InfantDeaths', 'Under5Deaths']]

### Renommage des colonnes

In [21]:
life_expectancy = life_expectancy.rename(columns={
    'Location': 'Country',
    'Time': 'Year',
    'LEx': 'Life_expectancy',
    'LExMale': 'Life_expectancy_male',
    'LExFemale': 'Life_expectancy_female',
    'IMR': 'Infant_mortality_rate'
})

### Filtrage des années

In [22]:
life_expectancy = life_expectancy[life_expectancy['Year'].between(1950,2021)]

In [23]:
life_expectancy.head(5)

,Country,Year,Life_expectancy,Life_expectancy_male,Life_expectancy_female,Deaths,DeathsMale,DeathsFemale,Infant_mortality_rate,PopGrowthRate,InfantDeaths,Under5Deaths
0,ADB region: Central and West Asia,1950,38.6085,38.1082,39.1261,1710.506,896.754,813.752,207.0834,2.058,600.102,930.552
1,ADB region: Central and West Asia,1951,39.6435,39.1333,40.1776,1693.605,888.959,804.646,200.9781,2.143,600.824,910.110
2,ADB region: Central and West Asia,1952,40.5673,40.0791,41.0807,1685.112,884.170,800.942,196.0193,2.212,602.648,898.759
3,ADB region: Central and West Asia,1953,41.4405,40.9378,41.9706,1679.966,882.165,797.801,190.7597,2.271,603.859,889.725
4,ADB region: Central and West Asia,1954,42.2044,41.7062,42.7313,1680.927,882.632,798.295,185.8880,2.342,605.992,885.494

## Pour le jeu de donnée "Health Inequality"

### Filtrage pour l'année 1950 jusqu'à 2021

In [24]:
health_inequality.tail(5)

,setting,date,source,indicator_abbr,indicator_name,dimension,subgroup,estimate,se,ci_lb,...,iso3,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,whoreg6,wbincome2025,update,dataset_id
917758,occupied Palestinian territory,2023,WHO Global Health Observatory,NUTSTUNTINGPREV,Stunting prevalence among children aged <5 yea...,Sex,Male,8.2,NaN,7.0,...,PSE,0,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917759,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTOVERWEIGHTPREV,Overweight prevalence among children aged <5 y...,Sex,Female,8.2,NaN,5.4,...,PSE,0,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917760,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTOVERWEIGHTPREV,Overweight prevalence among children aged <5 y...,Sex,Male,9.4,NaN,6.2,...,PSE,0,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917761,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTSTUNTINGPREV,Stunting prevalence among children aged <5 yea...,Sex,Female,7.6,NaN,6.4,...,PSE,0,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917762,occupied Palestinian territory,2024,WHO Global Health Observatory,NUTSTUNTINGPREV,Stunting prevalence among children aged <5 yea...,Sex,Male,8.4,NaN,7.1,...,PSE,0,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho

In [25]:
health_inequality = health_inequality[health_inequality['date'].between(1950,2021)]

In [26]:
health_inequality.tail(5)

,setting,date,source,indicator_abbr,indicator_name,dimension,subgroup,estimate,se,ci_lb,...,iso3,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,whoreg6,wbincome2025,update,dataset_id
917662,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_SANITATION_SAFELY_MANAGED,Population using safely managed sanitation ser...,Place of residence,Urban,73.45498,NaN,NaN,...,PSE,1,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917663,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_BASIC,Population using at least basic drinking-water...,Place of residence,Rural,99.38697,NaN,NaN,...,PSE,1,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917664,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_BASIC,Population using at least basic drinking-water...,Place of residence,Urban,97.80785,NaN,NaN,...,PSE,1,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917665,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_SAFELY_MANAGED,Population using safely managed drinking-water...,Place of residence,Rural,76.03888,NaN,NaN,...,PSE,1,100,0,0,0,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho
917666,occupied Palestinian territory,2021,WHO Global Health Observatory,WSH_WATER_SAFELY_MANAGED,Population using safely managed drinking-water...,Place of residence,Urban,81.21311,NaN,NaN,...,PSE,1,100,0,0,1,Eastern Mediterranean,Lower-middle-income,17 October 2025,rep_gho

Les dates ont bien été filtrées.

### Sélection des colonnes nécessaires

In [27]:
print(health_inequality.columns)

Index(['setting', 'date', 'source', 'indicator_abbr', 'indicator_name',
       'dimension', 'subgroup', 'estimate', 'se', 'ci_lb', 'ci_ub',
       'population', 'flag', 'setting_average', 'iso3', 'favourable_indicator',
       'indicator_scale', 'ordered_dimension', 'subgroup_order',
       'reference_subgroup', 'whoreg6', 'wbincome2025', 'update',
       'dataset_id'],
      dtype='str')

Toutes les colonnes semblent nécessaires, aucune séléction ne sera faites pour ce dataset.

### Visionnage des catégories dans les colonnes

In [28]:
print("setting :")
print(health_inequality["setting"].unique())
print("\n")

print("indicator_name :")
print(health_inequality["indicator_name"].unique())
print("\n")

print("subgroup :")
print(health_inequality["subgroup"].unique())
print("\n")

print("whoreg6 :")
print(health_inequality["whoreg6"].unique())

setting :
<StringArray>
[                       'Afghanistan',                            'Albania',
                            'Algeria',                            'Andorra',
                             'Angola',                'Antigua and Barbuda',
                          'Argentina',                            'Armenia',
                          'Australia',                            'Austria',
 ...
           'United States of America',                            'Uruguay',
                         'Uzbekistan',                            'Vanuatu',
 'Venezuela (Bolivarian Republic of)',                           'Viet Nam',
                              'Yemen',                             'Zambia',
                           'Zimbabwe',     'occupied Palestinian territory']
Length: 198, dtype: str


indicator_name :
<StringArray>
[                                                     'Infant mortality rate (deaths per 1000 live births)',
                          'Under-five mortality rate (model-based estimates) (deaths per 1000 live births)',
                                      'Cholesterol, mean high-density lipoprotein (HDL) (age-standardized)',
                                                 'Cholesterol, mean high-density lipoprotein (HDL) (crude)',
                              'Cholesterol, mean non-high-density lipoprotein (non-HDL) (age-standardized)',
                                         'Cholesterol, mean non-high-density lipoprotein (non-HDL) (crude)',
                                                               'Cholesterol, mean total (age-standardized)',
                                                                          'Cholesterol, mean total (crude)',
            'Hypertension: raised blood pressure (SBP>=140 OR DBP>=90) among adults aged 30-79 (crude) (%)',
 'Hypertension: raised blood pressure (SBP>=140 OR DBP>=90) among adults aged 30-79 (age-standardized) (%)',
 ...
                                      'Effective cataract surgical coverage of adults aged 50 and over (%)',
                         'Assistive technology: Travel distance to obtain assistive products (%) - 100+ km',
                        'Assistive technology: Travel distance to obtain assistive products (%) - 26-50 km',
                       'Assistive technology: Travel distance to obtain assistive products (%) - 51-100 km',
                         'Assistive technology: Travel distance to obtain assistive products (%) - 6-25 km',
                           'Assistive technology: Travel distance to obtain assistive products (%) - <6 km',
                                                 'Assistive technology: Met need of assistive products (%)',
                                                     'Assistive technology: Need of assistive products (%)',
                                                      'Assistive technology: Use of assistive products (%)',
                                   'Alcohol-attributable DALYs (age-standardized) (per 100 000 population)']
Length: 178, dtype: str


subgroup :
<StringArray>
[                                            'Female',
                                               'Male',
                                        '10-19 years',
                                          '5-9 years',
                                              'Rural',
                                              'Urban',
                                        '10-14 years',
                                        '15-19 years',
                          'Adults only (20-59 years)',
               'Adults with children and adolescents',
 'Multigenerational and/or adults with older persons',
                       'Multigenerational households',
                          'Adults with older persons',
                     'Only older adults (>=60 years)',
                               'Quintile 1 (poorest)',
                                         'Quintile 2',
                                         'Quintile 3',
                                         'Quintile 4',
                               'Quintile 5 (richest)',
                                        '15-24 years',
                                        '25-34 years',
                                        '35-44 years',
                                        '45-54 years',
                                        '55-64 years',
                                        '65-74 years',
                                        '75-84 years',
                                          '85+ years',
          'Only adolescents and children (<20 years)',
                                          '0-4 years',
                                        '18-29 years',
                                        '30-39 years',
                                        '40-49 years',
                                         '5-17 years',
                                        '50-59 years',
                                        '60-69 years',
                                        '70-79 years',
                                          '80+ years']
Length: 37, dtype: str


whoreg6 :
<StringArray>
['Eastern Mediterranean',              'European',               'African',
              'Americas',       'Western Pacific',       'South-East Asia',
                     nan]
Length: 7, dtype: str

### Renommage des colonnes

In [29]:
health_inequality = health_inequality.rename(columns={
    "setting": "country",
    "date": "date",
    "indicator_abbr": "indicator_code",
    "indicator_name": "indicator",
    "subgroup": "group",
    "estimate": "value",
    "iso3": "country_code",
    "whoreg6": "region",
    "wbincome2025": "income_level",
    "ci_lb": "ci_lower",
    "ci_ub": "ci_upper",
})

In [30]:
health_inequality.head(5)

,country,date,source,indicator_code,indicator,dimension,group,value,se,ci_lower,...,country_code,favourable_indicator,indicator_scale,ordered_dimension,subgroup_order,reference_subgroup,region,income_level,update,dataset_id
0,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,247.968162,NaN,194.625473,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
1,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Male,272.898981,NaN,214.032553,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
2,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Female,363.074361,NaN,286.019402,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
3,Afghanistan,1957,WHO Global Health Observatory,MDG_0000000007,Under-five mortality rate (model-based estimat...,Sex,Male,379.310303,NaN,297.924681,...,AFG,0,1000,0,0,1,Eastern Mediterranean,Low-income,17 October 2025,rep_gho
4,Afghanistan,1958,WHO Global Health Observatory,MDG_0000000001,Infant mortality rate (deaths per 1000 live bi...,Sex,Female,245.144576,NaN,197.317972,...,AFG,0,1000,0,0,0,Eastern Mediterranean,Low-income,17 October 2025,rep_gho